A couple markdown fixes

diff --git a/bin/md b/bin/md
--- a/bin/md
+++ b/bin/md
@@ -9,6 +9,7 @@
 MDCSS_PATH="$HOME/.markdown"
 
 init_css() {
+	## Initialize a local cache of Markdown templates.
 	[ -d $MDCSS_PATH ] || mkdir $MDCSS_PATH
 	if [ ! "$(ls $MDCSS_PATH)" ]; then
 		echo "No themes found in $MDCSS_PATH"
@@ -34,6 +35,7 @@ usage() {
 	echo "options:"
 	echo "    -t <theme>   Theme to use"
 	echo "    -c           Generate a table-of-contents"
+	echo "    -s           Enable syntax highlighting for code"
 	echo
 	echo "If using -c, include these two lines as placeholders for the TOC:"
 	echo "   <!-- toc -->"
@@ -53,11 +55,13 @@ init_css
 
 theme='default'
 toc=
+syntaxhi=
 
-while getopts "t:c" arg; do
+while getopts "t:cs" arg; do
 	case $arg in
 		t) theme=$OPTARG ;;
 		c) toc=1 ;;
+		s) syntaxhi=1 ;;
 		*) usage
 	esac
 done
@@ -80,6 +84,10 @@ if [ -x "`which marked`" ]; then
 	#markdown="`which marked` --gfm --tables --breaks"
 else
 	markdown="`which markdown`"
+fi
+if [ -z "$markdown" ]; then
+	echo "No markdown parser found in system path"
+	exit 2
 fi
 
 
@@ -105,6 +113,15 @@ fi
 
 
 # Build with a TOC.
+
+if [ -z "$(grep -n '<!-- toc' $mdfile)" ]; then
+	echo "Missing '<!-- toc --> tag in source file, cannot generate TOC"
+	exit 2
+fi
+if [ -z "$(grep -n '<!-- /toc' $mdfile)" ]; then
+	echo "Missing '<!-- /toc --> tag in source file, cannot generate TOC"
+	exit 2
+fi
 
 insert_file() {
 	srcf=$1  # This file...
